### ISSUE TITLE
Hi，Eran Hammer

### ISSUE THREAD

**Issue by xlianghang** [hueniverse/radix62#3]
I'm sorry to be contacting you this way.
I want to make a testing library to solve the problems of Web E2E testing.
I thought a lot about it, and I wanted to call the library "Bell".
And I found it was occupied, but it had been marked "deprecated" 3 years ago.
So I have a rude request, could you please delete it and let me use it

**Comment by hueniverse** [comment]
Sorry but bell was part of the hapi ecosystem and cannot be released for security reasons.
